// <auto-generated />
using System;
using CommunicationTrainer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunicationTrainer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617082027_FixScenarioDelete")]
    partial class FixScenarioDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunicationTrainer.Api.Models.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("IdealEmotional")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("IdealSafety")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("IdealStructural")
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToleranceEmotional")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ToleranceSafety")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ToleranceStructural")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WeightEmotional")
                        .HasColumnType("decimal(4,3)");

                    b.Property<decimal>("WeightSafety")
                        .HasColumnType("decimal(4,3)");

                    b.Property<decimal>("WeightStructural")
                        .HasColumnType("decimal(4,3)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.MessagePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MessageParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "opening",
                            Name = "Вступление",
                            OrderNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "middle",
                            Name = "Основная часть",
                            OrderNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "closing",
                            Name = "Завершение",
                            OrderNumber = 3
                        });
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.MessageResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EffectivenessPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("SessionId", "ScenarioId", "FormatId")
                        .IsUnique();

                    b.ToTable("MessageResults");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.PhraseOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EmotionalScore")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SafetyScore")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StructuralScore")
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("PartId");

                    b.HasIndex("ScenarioId", "PartId", "FormatId")
                        .IsUnique();

                    b.ToTable("PhraseOptions");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HintText")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RecipientFormatId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SituationText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientFormatId");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.SelectedPhrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("SessionId", "ScenarioId", "PartId")
                        .IsUnique();

                    b.ToTable("SelectedPhrases");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedScenarios")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentScenarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ScenarioQueue")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalScenarios")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentScenarioId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.MessageResult", b =>
                {
                    b.HasOne("CommunicationTrainer.Api.Models.Format", "Format")
                        .WithMany("MessageResults")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunicationTrainer.Api.Models.Scenario", "Scenario")
                        .WithMany("MessageResults")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunicationTrainer.Api.Models.TrainingSession", "Session")
                        .WithMany("MessageResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Scenario");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.PhraseOption", b =>
                {
                    b.HasOne("CommunicationTrainer.Api.Models.Format", "Format")
                        .WithMany("PhraseOptions")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunicationTrainer.Api.Models.MessagePart", "Part")
                        .WithMany("PhraseOptions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunicationTrainer.Api.Models.Scenario", "Scenario")
                        .WithMany("PhraseOptions")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Part");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.Scenario", b =>
                {
                    b.HasOne("CommunicationTrainer.Api.Models.Format", "RecipientFormat")
                        .WithMany("Scenarios")
                        .HasForeignKey("RecipientFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipientFormat");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.SelectedPhrase", b =>
                {
                    b.HasOne("CommunicationTrainer.Api.Models.MessagePart", "Part")
                        .WithMany("SelectedPhrases")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunicationTrainer.Api.Models.Scenario", "Scenario")
                        .WithMany("SelectedPhrases")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunicationTrainer.Api.Models.PhraseOption", "SelectedOption")
                        .WithMany("SelectedPhrases")
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunicationTrainer.Api.Models.TrainingSession", "Session")
                        .WithMany("SelectedPhrases")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Scenario");

                    b.Navigation("SelectedOption");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.TrainingSession", b =>
                {
                    b.HasOne("CommunicationTrainer.Api.Models.Scenario", "CurrentScenario")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("CurrentScenarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CommunicationTrainer.Api.Models.User", "User")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentScenario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.Format", b =>
                {
                    b.Navigation("MessageResults");

                    b.Navigation("PhraseOptions");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.MessagePart", b =>
                {
                    b.Navigation("PhraseOptions");

                    b.Navigation("SelectedPhrases");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.PhraseOption", b =>
                {
                    b.Navigation("SelectedPhrases");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.Scenario", b =>
                {
                    b.Navigation("MessageResults");

                    b.Navigation("PhraseOptions");

                    b.Navigation("SelectedPhrases");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.TrainingSession", b =>
                {
                    b.Navigation("MessageResults");

                    b.Navigation("SelectedPhrases");
                });

            modelBuilder.Entity("CommunicationTrainer.Api.Models.User", b =>
                {
                    b.Navigation("TrainingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
